<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <!-- Важно для ошибки про ".NETFramework,Version=v4.8": используем TargetFrameworks -->
    <TargetFrameworks>net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SalonAdmin</RootNamespace>
    <AssemblyName>SalonAdmin</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <!-- т.к. у нас свой AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

</Project>

